import {act,fireEvent,render,screen} from '@testing-library/react';
import App from './App';
let mockActiveSession;
jest.mock('./useStreamNetwork',()=>session=>{mockActiveSession=session;return {requestTransmit:action=>action('player'),stop:jest.fn(),toggleReceive:jest.fn(),togglePlay:jest.fn()};});
let images,audio,ctx,bus;
beforeEach(()=>{
 images=[];jest.spyOn(window,'Image').mockImplementation(()=>{const i={decode:jest.fn().mockResolvedValue()};images.push(i);return i;});
 bus={connect:jest.fn(),disconnect:jest.fn()};ctx={state:'running',sampleRate:48000,destination:{},resume:jest.fn().mockResolvedValue(),close:jest.fn().mockResolvedValue(),createAnalyser:()=>({fftSize:2048}),createGain:()=>bus,createMediaElementSource:jest.fn(()=>({connect:jest.fn()}))};window.AudioContext=jest.fn(()=>ctx);
 jest.spyOn(window,'Audio').mockImplementation(()=>{audio=new EventTarget();audio.paused=true;audio.play=jest.fn(async()=>{audio.paused=false;});audio.pause=jest.fn(()=>{audio.paused=true;});return audio;});
 URL.createObjectURL=jest.fn(f=>'blob:'+f.name);URL.revokeObjectURL=jest.fn();jest.spyOn(window,'requestAnimationFrame').mockReturnValue(1);jest.spyOn(window,'cancelAnimationFrame').mockImplementation(()=>{});
});
afterEach(()=>{jest.restoreAllMocks();delete window.AudioContext;});
test('RADIO confines empty label, counter and long filename to the original display',()=>{
 render(<App/>);
 const display=screen.getByRole('button',{name:'Abrir controles do player'});
 expect(display).toHaveTextContent(/^LOAD \/ ABRIR$/);
 expect(screen.queryByText(/^PLAYLIST$/i)).not.toBeInTheDocument();
 expect(display).toHaveStyle({left:'32.85%',right:'32.62%',top:'50.25%',bottom:'41.73%',overflow:'hidden',contain:'paint',background:'transparent',border:'0px'});
 const name='Uma música com um nome muito comprido para conferir o recorte do visor';
 fireEvent.change(screen.getByLabelText('Arquivos de áudio'),{target:{files:[new File(['a'],name+'.wav',{type:'audio/wav'})]}});
 expect(display).toHaveTextContent('01/01');
 expect(display).toContainElement(screen.getByTitle(name));
 expect(screen.getByTitle(name)).toHaveStyle({minWidth:'0',whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis'});
 expect(display).toHaveStyle({gridTemplateColumns:'auto minmax(0,1fr)'});
 expect(screen.queryByText(/^PLAYLIST$/i)).not.toBeInTheDocument();
});
test('multi-file player retains source and transmission through next track and navigation',async()=>{
 const view=render(<App/>);const files=[new File(['a'],'first.wav',{type:'audio/wav'}),new File(['b'],'second.webm',{type:'audio/webm'})];
 fireEvent.change(screen.getByLabelText('Arquivos de áudio'),{target:{files}});
 expect(screen.queryByRole('button',{name:'Playlist',exact:true})).not.toBeInTheDocument();
 expect(screen.getByRole('button',{name:'Abrir controles do player'})).toHaveTextContent('01/02');
 expect(screen.getByLabelText('Arquivos de áudio')).toHaveAttribute('multiple');
 fireEvent.click(screen.getByRole('button',{name:'STREAM',exact:true}));await act(async()=>images.find(i=>i.src==='/images/stream.png').onload());
 fireEvent.click(screen.getByRole('button',{name:'TRANSMITIR',exact:true}));await act(async()=>{await Promise.resolve();});
 const session=mockActiveSession;expect(session.kind).toBe('player');expect(audio.src).toBe('blob:first.wav');
 fireEvent.click(screen.getByRole('button',{name:'PLAY / STOP'}));expect(audio.paused).toBe(true);expect(mockActiveSession).toBe(session);
 fireEvent.click(screen.getByRole('button',{name:'PLAY / STOP'}));await act(async()=>{await Promise.resolve();});expect(audio.paused).toBe(false);
 await act(async()=>audio.dispatchEvent(new Event('ended')));
 expect(audio.src).toBe('blob:second.webm');expect(mockActiveSession).toBe(session);expect(ctx.createMediaElementSource).toHaveBeenCalledTimes(1);
 fireEvent.click(screen.getByRole('button',{name:'VOLTAR',exact:true}));expect(mockActiveSession).toBe(session);expect(ctx.close).not.toHaveBeenCalled();expect(screen.getByText('second')).toBeInTheDocument();
 fireEvent.click(screen.getByRole('button',{name:'Abrir controles do player'}));await screen.findByText('PLAYER LOCAL');
 fireEvent.click(screen.getByText('◀ ANTERIOR'));await act(async()=>{await Promise.resolve();});expect(audio.src).toBe('blob:first.wav');
 fireEvent.click(screen.getByText('PRÓXIMA ▶'));await act(async()=>{await Promise.resolve();});expect(audio.src).toBe('blob:second.webm');expect(mockActiveSession).toBe(session);
 view.unmount();expect(ctx.close).toHaveBeenCalled();
});
